services:
  app:
    build:
      context: .
      args:
        VITE_SUPABASE_TARGET_URL: ${VITE_SUPABASE_TARGET_URL}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
    ports:
      - "4173:4173"
    restart: always
